### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by floaterest** [floaterest/stopwatch#12]
Since GitHub is deprecating their Project (classic), this issue is used (and intentionally kept unresolved) to track todos.

- [ ] click on `<fieldset>` to pause stopwatch
- [ ] for each button, add hover tooltip (`title=""`)
  - hover on `<legend>` will show reset time
- [ ] top left logo toggles concurrency
  - no concurrent: current logo
    - start one stopwatch will pause others
  - yes concurrent: logo is 2 stopwatches overlapping each other (like a copy button)
- [ ] play sound when stopwatch reaches 0
